import { MendixEntity, MendixAttribute, MendixEnumeration, GeneratedFile } from '../lib/types'
import { pluralize } from '../lib/pageUtils'

function sanitizeFieldName(name: string): string {
  // Prisma field names cannot start with underscore.
  // Also normalise 'ID'/'Id' to 'id' to avoid SQLite duplicate-column errors
  // when an entity has an explicit id attribute alongside an auto-generated one.
  let result = name.replace(/^_+/, '')
  if (result.toLowerCase() === 'id') result = 'id'
  return result
}

function attributeToField(attr: MendixAttribute, enumNames: Set<string>): string {
  const fieldName = sanitizeFieldName(attr.name)

  if (attr.isAutoNumber) {
    return `  ${fieldName}  Int  @id @default(autoincrement())`
  }

  let prismaType: string
  if (attr.isEnumeration && attr.enumerationName && enumNames.has(attr.enumerationName)) {
    // Use the proper Prisma enum type
    prismaType = attr.enumerationName
  } else if (attr.isEnumeration) {
    // Enum not found in extracted enumerations — fall back to String
    prismaType = `String // enum: ${attr.enumerationName || 'unknown'}`
  } else {
    // SQLite does not support Decimal — map to Float
    prismaType = attr.prismaType === 'Decimal' ? 'Float' : attr.prismaType
  }

  const directives: string[] = []
  if (fieldName.toLowerCase() === 'id') {
    directives.push('@id')
  }

  return `  ${fieldName}  ${prismaType}  ${directives.join(' ')}`.trimEnd()
}

function entityToModel(entity: MendixEntity, relationLines: string[], enumNames: Set<string>): string {
  const lines: string[] = [`model ${entity.name} {`]

  // Add auto-incremented id if no auto-number attribute
  const hasAutoNumber = entity.attributes.some(a => a.isAutoNumber)
  const hasIdAttr = entity.attributes.some(a => sanitizeFieldName(a.name) === 'id')
  if (!hasAutoNumber && !hasIdAttr) {
    lines.push(`  id  Int  @id @default(autoincrement())`)
  }

  // Add attributes
  for (const attr of entity.attributes) {
    lines.push(attributeToField(attr, enumNames))
  }

  // Append pre-computed relation fields (both forward and back-references)
  lines.push(...relationLines)

  lines.push(`}`)
  return lines.join('\n')
}

function enumerationToBlock(enumeration: MendixEnumeration): string {
  const lines: string[] = [`enum ${enumeration.name} {`]
  for (const val of enumeration.values) {
    lines.push(`  ${val}`)
  }
  lines.push(`}`)
  return lines.join('\n')
}

export function generatePrismaSchema(entities: MendixEntity[], enumerations: MendixEnumeration[] = []): GeneratedFile {
  const userEntities = entities.filter(e => !e.isSystemEntity)
  const enumNames = new Set(enumerations.map(e => e.name))

  // Pre-compute relation fields for every entity in a single pass.
  // For each M2M association owned by A → B, both sides are registered here:
  //   A gets: pluralize(B)  B[]   (forward)
  //   B gets: pluralize(A)  A[]   (back-reference)
  // Doing both sides together guarantees Prisma's implicit-M2M requirement is met.
  const relationFields = new Map<string, string[]>()
  const relationFieldNames = new Map<string, Set<string>>()

  // Pre-seed each entity's field name set with its own attribute names so that
  // auto-generated FK columns never clash with existing Mendix attributes.
  for (const entity of userEntities) {
    const attrNames = new Set(entity.attributes.map(a => sanitizeFieldName(a.name).toLowerCase()))
    relationFields.set(entity.name, [])
    relationFieldNames.set(entity.name, attrNames)
  }

  const addRelation = (entityName: string, line: string) => {
    if (!relationFields.has(entityName)) {
      relationFields.set(entityName, [])
      relationFieldNames.set(entityName, new Set())
    }
    const fieldName = line.trim().split(/\s+/)[0].toLowerCase()
    if (relationFieldNames.get(entityName)!.has(fieldName)) return
    relationFieldNames.get(entityName)!.add(fieldName)
    relationFields.get(entityName)!.push(line)
  }

  for (const entity of userEntities) {
    for (const assoc of entity.associations) {
      const targetName = assoc.targetEntityName
      if (assoc.type === 'one-to-many') {
        // Only emit the raw FK integer column. No navigation fields, no back-refs.
        // This avoids all "ambiguous relation" errors on complex multi-module schemas.
        const fkField = `${targetName.toLowerCase()}Id`
        addRelation(entity.name, `  ${fkField}  Int?`)
      }
      // M2M: skipped — implicit M2M requires both sides and causes naming conflicts
      // in apps with many cross-module associations.
    }
  }

  const header = `// Generated by mendix-to-node
// Review before using in production

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
`

  const entityModels = userEntities.map(e => entityToModel(e, relationFields.get(e.name) ?? [], enumNames)).join('\n\n')

  // Prisma requires at least one model to generate a client.
  // Add a placeholder when the project has no user entities.
  // Note: names starting with _ are reserved in Prisma 5 — do not use them.
  const placeholder = userEntities.length === 0
    ? `model AppConfig {\n  id    Int    @id @default(autoincrement())\n  key   String @unique\n  value String\n}\n`
    : ''

  const models = entityModels || placeholder

  // Emit only enumerations that are actually referenced by at least one entity attribute
  const referencedEnumNames = new Set<string>()
  for (const entity of userEntities) {
    for (const attr of entity.attributes) {
      if (attr.isEnumeration && attr.enumerationName && enumNames.has(attr.enumerationName)) {
        referencedEnumNames.add(attr.enumerationName)
      }
    }
  }
  const enumBlocks = enumerations
    .filter(e => referencedEnumNames.has(e.name) && e.values.length > 0)
    .map(enumerationToBlock)
    .join('\n\n')

  const sections = [models, enumBlocks].filter(Boolean).join('\n\n')

  return {
    path: 'prisma/schema.prisma',
    content: header + '\n' + sections + '\n',
    category: 'data'
  }
}
