import { MendixEntity, MendixAttribute, MendixEnumeration, GeneratedFile } from '../lib/types'

function enumerationToUnionType(enumeration: MendixEnumeration): string {
  if (enumeration.values.length === 0) return ''
  const union = enumeration.values.map(v => `'${v}'`).join(' | ')
  return `export type ${enumeration.name} = ${union}`
}

function attributeToProperty(attr: MendixAttribute, enumNames: Set<string>): string {
  const optional = attr.isAutoNumber ? '?' : ''
  const tsType = attr.isEnumeration && attr.enumerationName && enumNames.has(attr.enumerationName)
    ? attr.enumerationName
    : attr.tsType
  return `  ${attr.name}${optional}: ${tsType}`
}

function entityToInterface(entity: MendixEntity, enumNames: Set<string>): string {
  const lines: string[] = [`export interface ${entity.name} {`]

  if (!entity.attributes.some(a => a.isAutoNumber)) {
    lines.push(`  id?: number`)
  }

  for (const attr of entity.attributes) {
    lines.push(attributeToProperty(attr, enumNames))
  }

  // Add relation type references
  for (const assoc of entity.associations) {
    if (assoc.type === 'one-to-many' && assoc.owner === 'source') {
      lines.push(`  ${assoc.name.toLowerCase()}s?: ${assoc.targetEntityName}[]`)
    } else if (assoc.type === 'many-to-many') {
      lines.push(`  ${assoc.name.toLowerCase()}s?: ${assoc.targetEntityName}[]`)
    }
  }

  lines.push(`}`)
  return lines.join('\n')
}

export function generateTypes(entities: MendixEntity[], enumerations: MendixEnumeration[] = []): GeneratedFile {
  const userEntities = entities.filter(e => !e.isSystemEntity)
  const enumNames = new Set(enumerations.map(e => e.name))

  const header = `// Generated by mendix-to-node
// TypeScript types and interfaces for all Mendix entities
`

  const enumTypes = enumerations
    .filter(e => e.values.length > 0)
    .map(enumerationToUnionType)
    .filter(Boolean)
    .join('\n')

  const interfaces = userEntities.map(e => entityToInterface(e, enumNames)).join('\n\n')

  const sections = [enumTypes, interfaces].filter(Boolean).join('\n\n')

  return {
    path: 'src/types.ts',
    content: header + '\n' + sections + '\n',
    category: 'data'
  }
}
